site_name: jllama-py
repo_url: https://github.com/zjwan461/jllama-py

theme:
  name: material
  palette:

    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            members_order: source
            group_by_category: false
            signature_crossrefs: true
            show_signature: true
            docstring_section_style: list
            show_root_heading: true
            heading_level: 3
            preload_modules:
              - typing
              - typing_extensions
              - ctypes
          import:
            - https://docs.python.org/3/objects.inv
            - https://numpy.org/doc/stable/objects.inv

watch:
  - README.md

nav:
  - "Getting Started": "index.md"
  - "Install llama-cpp-python(CPU)": "api-reference.md"
  - "Install llama-cpp-python(CUDA)": "api-reference.md"

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: zjwan461
      repo: jllama-py
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - tables