CREATE TABLE IF NOT EXISTS SYS_INFO
(
    ID           BIGINT UNSIGNED NOT NULL,
    PLATFORM     VARCHAR(50)     NOT NULL,
    OS_ARCH      VARCHAR(50)     NOT NULL,
    GPU_PLATFORM VARCHAR(50)     NULL,
    CREATE_TIME  DATETIME,
    UPDATE_TIME  DATETIME,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS USER
(
    ID          BIGINT UNSIGNED NOT NULL,
    USERNAME    VARCHAR(50)     NOT NULL,
    EMAIL       VARCHAR(50)     NOT NULL,
    PASSWORD    CHAR(32)        NOT NULL,
    ROLE        VARCHAR(5)      NOT NULL,
    CREATE_TIME DATETIME,
    UPDATE_TIME DATETIME,
    PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS SYS_INFO_USERNAME_IDX ON `USER`(USERNAME);


CREATE TABLE IF NOT EXISTS MODEL
(
    ID                BIGINT UNSIGNED NOT NULL,
    NAME              VARCHAR(50)     NOT NULL,
    REPO              VARCHAR(50)     NOT NULL,
    DOWNLOAD_PLATFORM VARCHAR(50)     NULL,
    FILES             LONGTEXT        NULL,
    SAVE_DIR          VARCHAR(255)    NULL,
    CREATE_TIME       DATETIME,
    UPDATE_TIME       DATETIME,
    PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS MODEL_NAME_IDX ON `MODEL`(NAME);

CREATE TABLE IF NOT EXISTS FILE_DOWNLOAD
(
    ID          BIGINT UNSIGNED NOT NULL,
    MODEL_ID    BIGINT UNSIGNED NOT NULL,
    MODEL_NAME  VARCHAR(50)     NOT NULL,
    FILE_PATH   VARCHAR(255)    NOT NULL,
    FILE_NAME   VARCHAR(50)     NOT NULL,
    FILE_SIZE   BIGINT UNSIGNED NOT NULL,
    TYPE        VARCHAR(50)     NOT NULL DEFAULT 'download',
    CREATE_TIME DATETIME,
    UPDATE_TIME DATETIME,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS LLAMA_EXEC_HIS
(
    ID                BIGINT UNSIGNED NOT NULL,
    MODEL_ID          BIGINT UNSIGNED NOT NULL,
    MODEL_NAME        VARCHAR(50)     NOT NULL,
    FILE_ID           BIGINT UNSIGNED NOT NULL,
    FILE_PATH         VARCHAR(255)    NOT NULL,
    FILE_NAME         VARCHAR(50)     NOT NULL,
    LLAMA_CPP_DIR     VARCHAR(255)    NOT NULL,
    LLAMA_CPP_COMMAND VARCHAR(50)     NOT NULL,
    LLAMA_CPP_ARGS    VARCHAR(1000)   NULL,
    STATUS            INT UNSIGNED    NOT NULL DEFAULT 0 COMMENT '0 FOR NOT START, 1 FOR START',
    PID               VARCHAR(50)     NULL COMMENT '执行LLAMA.CPP进程的PID',
    LOG_FILE_PATH     VARCHAR(255)    NULL COMMENT '执行LLAMA.CPP进程日志文件目录',
    CREATE_TIME       DATETIME,
    UPDATE_TIME       DATETIME,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS SETTINGS
(
    ID             CHAR(4)           NOT NULL,
    LLAMA_CPP_DIR  VARCHAR(1000)     NOT NULL,
    MODEL_SAVE_DIR VARCHAR(1000)     NOT NULL,
    LOG_SAVE_DIR   VARCHAR(1000)     NOT NULL,
    LOG_LINE       INT     NOT NULL DEFAULT 50,
    LOG_SAVE_DAY   INT     NOT NULL DEFAULT 7,
    GPU_FLAG       INT     NOT NULL DEFAULT 0 COMMENT '0 FOR DISABLE, 1 FOR ENABLE',
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS GGUF_SPLIT_MERGE
(
    ID             BIGINT UNSIGNED   NOT NULL,
    `OPTION`       VARCHAR(50)       NOT NULL,
    `INPUT`        VARCHAR(1000)     NOT NULL,
    `OUTPUT`       VARCHAR(1000)     NOT NULL,
    SPLIT_OPTION   VARCHAR(50)       NULL,
    SPLIT_PARAM    VARCHAR(50)       NULL,
    ASYNC          INT               NOT NULL DEFAULT 1,
    CREATE_TIME    DATETIME,
    UPDATE_TIME    DATETIME,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS QUANTIZE
(
    ID             BIGINT UNSIGNED   NOT NULL,
    `INPUT`        VARCHAR(1000)     NOT NULL,
    `OUTPUT`       VARCHAR(1000)     NOT NULL,
    PARAM          VARCHAR(50)       NOT NULL COMMENT '量化精度',
    ASYNC          INT               NOT NULL DEFAULT 1,
    CREATE_TIME    DATETIME,
    UPDATE_TIME    DATETIME,
    PRIMARY KEY (ID)
);


ALTER TABLE SETTINGS ADD COLUMN IF NOT EXISTS UPDATE_PUSH INT NOT NULL DEFAULT 0;

ALTER TABLE SYS_INFO ADD COLUMN IF NOT EXISTS CPP_VERSION VARCHAR(255) NOT NULL DEFAULT 'B4942';
ALTER TABLE SYS_INFO ADD COLUMN IF NOT EXISTS FACTORY_VERSION VARCHAR(255) NOT NULL DEFAULT 'v0.9.2';
ALTER TABLE SYS_INFO ADD COLUMN IF NOT EXISTS SELF_VERSION VARCHAR(255) NOT NULL DEFAULT 'v1.0';


ALTER TABLE SETTINGS ADD COLUMN IF NOT EXISTS PY_DIR VARCHAR(1000) NULL;

CREATE TABLE IF NOT EXISTS MODEL_CONVERT
(
    ID             BIGINT UNSIGNED   NOT NULL,
    `INPUT`        VARCHAR(1000)     NOT NULL,
    `OUTPUT`       VARCHAR(1000)     NOT NULL,
    SCRIPT_FILE    VARCHAR(1000)     NOT NULL,
    ASYNC          INT               NOT NULL DEFAULT 1,
    CREATE_TIME    DATETIME,
    UPDATE_TIME    DATETIME,
    PRIMARY KEY (ID)
);

ALTER TABLE SETTINGS ADD COLUMN IF NOT EXISTS PROXY_IP VARCHAR(255) NULL;

ALTER TABLE SETTINGS ADD COLUMN IF NOT EXISTS PROXY_PORT INT NULL;

ALTER TABLE SETTINGS ADD COLUMN IF NOT EXISTS FACTORY_PORT INT NULL DEFAULT 7860;